# Generated by Django 5.1.4 on 2025-01-04 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmodels.country')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='GovernmentFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identifing_uuid', models.UUIDField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmodels.area')),
            ],
            options={
                'db_table': 'government_facility',
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmodels.area')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testmodels.governmentfacility')),
            ],
            options={
                'db_table': 'citizen',
            },
        ),
    ]
